### ISSUE TITLE
In Class diagram in README the LocalDayPlan should be mentioned as an interface

### ISSUE THREAD

**Issue by hiphof** [FontysVenlo/alda_appointmentplanner_api#2]
<img width="843" alt="Screenshot 2023-09-21 at 16 00 55" src="https://github.com/FontysVenlo/alda_appointmentplanner_api/assets/35424969/5ce628c1-a89b-411e-b747-bed4ee2febe5">

**Comment by Bonajo** [comment]
Thanks for the feedback, this issue is fixed in exercise for this year.
